export const jsonAbandono = [
  {
    tipo: "Abandono",
    metrica: 8,
    fecha: "2024-05-04",
    hora: "20:32:12",
  },
  {
    id: 45,
    tipo: "Abandono",
    metrica: 8,
    fecha: "2024-05-03",
    hora: "20:15:12",
  },
  {
    id: 255,
    tipo: "Abandono",
    metrica: 20,
    fecha: "2024-05-03",
    hora: "20:00:12",
  },
  {
    id: 261,
    tipo: "Abandono",
    metrica: 18,
    fecha: "2024-05-04",
    hora: "19:30:12",
  },
  {
    tipo: "Abandono",
    metrica: 18,
    fecha: "2024-05-04",
    hora: "18:30:12",
  },
  {
    tipo: "Abandono",
    metrica: 18,
    fecha: "2024-05-04",
    hora: "16:30:12",
  },
  {
    tipo: "Abandono",
    metrica: 18,
    fecha: "2024-05-04",
    hora: "14:30:12",
  },
  {
    tipo: "Abandono",
    metrica: 21,
    fecha: "2024-05-04",
    hora: "12:30:12",
  },
];

export const jsonNivel = [
  {
    tipo: "Nivel",
    metrica: 85,
    fecha: "2024-05-04",
    hora: "20:32:12",
  },
  {
    id: 45,
    tipo: "Nivel",
    metrica: 93,
    fecha: "2024-05-03",
    hora: "20:15:12",
  },
  {
    id: 255,
    tipo: "Nivel",
    metrica: 91,
    fecha: "2024-05-03",
    hora: "20:00:12",
  },
  {
    id: 261,
    tipo: "Nivel",
    metrica: 80,
    fecha: "2024-05-04",
    hora: "19:30:12",
  },
  {
    tipo: "Nivel",
    metrica: 72,
    fecha: "2024-05-04",
    hora: "18:30:12",
  },
  {
    tipo: "Nivel",
    metrica: 88,
    fecha: "2024-05-04",
    hora: "16:30:12",
  },
  {
    tipo: "Nivel",
    metrica: 81,
    fecha: "2024-05-04",
    hora: "14:30:12",
  },
  {
    tipo: "Nivel",
    metrica: 75,
    fecha: "2024-05-04",
    hora: "12:30:12",
  },
];

export const jsonVel = [
  {
    tipo: "Velocidad",
    metrica: 12,
    fecha: "2024-05-04",
    hora: "20:32:12",
  },
  {
    id: 45,
    tipo: "Velocidad",
    metrica: 8,
    fecha: "2024-05-03",
    hora: "20:15:12",
  },
  {
    id: 255,
    tipo: "Velocidad",
    metrica: 5,
    fecha: "2024-05-03",
    hora: "20:00:12",
  },
  {
    id: 261,
    tipo: "Velocidad",
    metrica: 6,
    fecha: "2024-05-04",
    hora: "19:30:12",
  },
  {
    tipo: "Velocidad",
    metrica: 4,
    fecha: "2024-05-04",
    hora: "18:30:12",
  },
  {
    tipo: "Velocidad",
    metrica: 4,
    fecha: "2024-05-04",
    hora: "16:30:12",
  },
  {
    tipo: "Velocidad",
    metrica: 13,
    fecha: "2024-05-04",
    hora: "14:30:12",
  },
  {
    tipo: "Velocidad",
    metrica: 5,
    fecha: "2024-05-04",
    hora: "12:30:12",
  },
];

export const jsonOc = [
  {
    tipo: "Ocupacion",
    metrica: 83,
    fecha: "2024-05-04",
    hora: "20:32:12",
  },
  {
    id: 45,
    tipo: "Ocupacion",
    metrica: 91,
    fecha: "2024-05-03",
    hora: "20:15:12",
  },
  {
    id: 255,
    tipo: "Ocupacion",
    metrica: 64,
    fecha: "2024-05-03",
    hora: "20:00:12",
  },
  {
    id: 261,
    tipo: "Ocupacion",
    metrica: 71,
    fecha: "2024-05-04",
    hora: "19:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 92,
    fecha: "2024-05-04",
    hora: "18:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 69,
    fecha: "2024-05-04",
    hora: "16:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 74,
    fecha: "2024-05-04",
    hora: "14:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 81,
    fecha: "2024-05-04",
    hora: "12:30:12",
  },
];

export const jsonTiempo = [
  {
    tipo: "Ocupacion",
    metrica: 210,
    fecha: "2024-05-04",
    hora: "20:32:12",
  },
  {
    id: 45,
    tipo: "Ocupacion",
    metrica: 90,
    fecha: "2024-05-03",
    hora: "20:15:12",
  },
  {
    id: 255,
    tipo: "Ocupacion",
    metrica: 341,
    fecha: "2024-05-03",
    hora: "20:00:12",
  },
  {
    id: 261,
    tipo: "Ocupacion",
    metrica: 89,
    fecha: "2024-05-04",
    hora: "19:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 128,
    fecha: "2024-05-04",
    hora: "18:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 189,
    fecha: "2024-05-04",
    hora: "16:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 254,
    fecha: "2024-05-04",
    hora: "14:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 87,
    fecha: "2024-05-04",
    hora: "12:30:12",
  },
];

export const jsonRes = [
  {
    tipo: "Ocupacion",
    metrica: 76,
    fecha: "2024-05-04",
    hora: "20:32:12",
  },
  {
    id: 45,
    tipo: "Ocupacion",
    metrica: 81,
    fecha: "2024-05-03",
    hora: "20:15:12",
  },
  {
    id: 255,
    tipo: "Ocupacion",
    metrica: 88,
    fecha: "2024-05-03",
    hora: "20:00:12",
  },
  {
    id: 261,
    tipo: "Ocupacion",
    metrica: 89,
    fecha: "2024-05-04",
    hora: "19:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 73,
    fecha: "2024-05-04",
    hora: "18:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 71,
    fecha: "2024-05-04",
    hora: "16:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 90,
    fecha: "2024-05-04",
    hora: "14:30:12",
  },
  {
    tipo: "Ocupacion",
    metrica: 91,
    fecha: "2024-05-04",
    hora: "12:30:12",
  },
];

export const mesOc = [
  { tipo: "Ocupacion", metrica: 78 },
  { tipo: "Ocupacion", metrica: 98 },
  { tipo: "Ocupacion", metrica: 86 },
  { tipo: "Ocupacion", metrica: 65 },
  { tipo: "Ocupacion", metrica: 93 },
  { tipo: "Ocupacion", metrica: 68 },
  { tipo: "Ocupacion", metrica: 95 },
  { tipo: "Ocupacion", metrica: 96 },
  { tipo: "Ocupacion", metrica: 95 },
  { tipo: "Ocupacion", metrica: 70 },
  { tipo: "Ocupacion", metrica: 79 },
  { tipo: "Ocupacion", metrica: 71 },
  { tipo: "Ocupacion", metrica: 89 },
  { tipo: "Ocupacion", metrica: 74 },
  { tipo: "Ocupacion", metrica: 69 },
  { tipo: "Ocupacion", metrica: 73 },
  { tipo: "Ocupacion", metrica: 73 },
  { tipo: "Ocupacion", metrica: 98 },
  { tipo: "Ocupacion", metrica: 98 },
  { tipo: "Ocupacion", metrica: 86 },
  { tipo: "Ocupacion", metrica: 66 },
  { tipo: "Ocupacion", metrica: 65 },
  { tipo: "Ocupacion", metrica: 91 },
  { tipo: "Ocupacion", metrica: 70 },
  { tipo: "Ocupacion", metrica: 94 },
  { tipo: "Ocupacion", metrica: 62 },
  { tipo: "Ocupacion", metrica: 73 },
  { tipo: "Ocupacion", metrica: 76 },
  { tipo: "Ocupacion", metrica: 83 },
  { tipo: "Ocupacion", metrica: 87 },
  { tipo: "Ocupacion", metrica: 72 },
  { tipo: "Ocupacion", metrica: 97 },
  { tipo: "Ocupacion", metrica: 89 },
  { tipo: "Ocupacion", metrica: 63 },
  { tipo: "Ocupacion", metrica: 61 },
  { tipo: "Ocupacion", metrica: 65 },
  { tipo: "Ocupacion", metrica: 82 },
  { tipo: "Ocupacion", metrica: 61 },
  { tipo: "Ocupacion", metrica: 64 },
  { tipo: "Ocupacion", metrica: 80 },
  { tipo: "Ocupacion", metrica: 63 },
  { tipo: "Ocupacion", metrica: 98 },
  { tipo: "Ocupacion", metrica: 77 },
  { tipo: "Ocupacion", metrica: 92 },
  { tipo: "Ocupacion", metrica: 76 },
  { tipo: "Ocupacion", metrica: 93 },
  { tipo: "Ocupacion", metrica: 92 },
  { tipo: "Ocupacion", metrica: 88 },
  { tipo: "Ocupacion", metrica: 67 },
  { tipo: "Ocupacion", metrica: 89 },
  { tipo: "Ocupacion", metrica: 66 },
  { tipo: "Ocupacion", metrica: 69 },
  { tipo: "Ocupacion", metrica: 62 },
  { tipo: "Ocupacion", metrica: 87 },
  { tipo: "Ocupacion", metrica: 65 },
  { tipo: "Ocupacion", metrica: 61 },
  { tipo: "Ocupacion", metrica: 85 },
  { tipo: "Ocupacion", metrica: 65 },
  { tipo: "Ocupacion", metrica: 78 },
  { tipo: "Ocupacion", metrica: 76 },
];
export const mesNivel = [
  { tipo: "Nivel", metrica: 72 },
  { tipo: "Nivel", metrica: 81 },
  { tipo: "Nivel", metrica: 51 },
  { tipo: "Nivel", metrica: 87 },
  { tipo: "Nivel", metrica: 84 },
  { tipo: "Nivel", metrica: 60 },
  { tipo: "Nivel", metrica: 44 },
  { tipo: "Nivel", metrica: 60 },
  { tipo: "Nivel", metrica: 82 },
  { tipo: "Nivel", metrica: 44 },
  { tipo: "Nivel", metrica: 94 },
  { tipo: "Nivel", metrica: 93 },
  { tipo: "Nivel", metrica: 69 },
  { tipo: "Nivel", metrica: 91 },
  { tipo: "Nivel", metrica: 65 },
  { tipo: "Nivel", metrica: 73 },
  { tipo: "Nivel", metrica: 86 },
  { tipo: "Nivel", metrica: 92 },
  { tipo: "Nivel", metrica: 63 },
  { tipo: "Nivel", metrica: 87 },
  { tipo: "Nivel", metrica: 84 },
  { tipo: "Nivel", metrica: 52 },
  { tipo: "Nivel", metrica: 84 },
  { tipo: "Nivel", metrica: 85 },
  { tipo: "Nivel", metrica: 58 },
  { tipo: "Nivel", metrica: 93 },
  { tipo: "Nivel", metrica: 58 },
  { tipo: "Nivel", metrica: 42 },
  { tipo: "Nivel", metrica: 67 },
  { tipo: "Nivel", metrica: 70 },
  { tipo: "Nivel", metrica: 89 },
  { tipo: "Nivel", metrica: 42 },
  { tipo: "Nivel", metrica: 99 },
  { tipo: "Nivel", metrica: 63 },
  { tipo: "Nivel", metrica: 54 },
  { tipo: "Nivel", metrica: 63 },
  { tipo: "Nivel", metrica: 48 },
  { tipo: "Nivel", metrica: 75 },
  { tipo: "Nivel", metrica: 77 },
  { tipo: "Nivel", metrica: 49 },
  { tipo: "Nivel", metrica: 58 },
  { tipo: "Nivel", metrica: 74 },
  { tipo: "Nivel", metrica: 79 },
  { tipo: "Nivel", metrica: 42 },
  { tipo: "Nivel", metrica: 87 },
  { tipo: "Nivel", metrica: 54 },
  { tipo: "Nivel", metrica: 79 },
  { tipo: "Nivel", metrica: 58 },
  { tipo: "Nivel", metrica: 92 },
  { tipo: "Nivel", metrica: 40 },
  { tipo: "Nivel", metrica: 90 },
  { tipo: "Nivel", metrica: 53 },
  { tipo: "Nivel", metrica: 66 },
  { tipo: "Nivel", metrica: 96 },
  { tipo: "Nivel", metrica: 57 },
  { tipo: "Nivel", metrica: 40 },
  { tipo: "Nivel", metrica: 87 },
  { tipo: "Nivel", metrica: 39 },
  { tipo: "Nivel", metrica: 74 },
  { tipo: "Nivel", metrica: 73 },
];
export const mesTiempo = [
  { tipo: "Tiempo", metrica: 214 },
  { tipo: "Tiempo", metrica: 461 },
  { tipo: "Tiempo", metrica: 564 },
  { tipo: "Tiempo", metrica: 430 },
  { tipo: "Tiempo", metrica: 383 },
  { tipo: "Tiempo", metrica: 234 },
  { tipo: "Tiempo", metrica: 300 },
  { tipo: "Tiempo", metrica: 496 },
  { tipo: "Tiempo", metrica: 557 },
  { tipo: "Tiempo", metrica: 313 },
  { tipo: "Tiempo", metrica: 220 },
  { tipo: "Tiempo", metrica: 500 },
  { tipo: "Tiempo", metrica: 363 },
  { tipo: "Tiempo", metrica: 502 },
  { tipo: "Tiempo", metrica: 573 },
  { tipo: "Tiempo", metrica: 83 },
  { tipo: "Tiempo", metrica: 307 },
  { tipo: "Tiempo", metrica: 179 },
  { tipo: "Tiempo", metrica: 377 },
  { tipo: "Tiempo", metrica: 282 },
  { tipo: "Tiempo", metrica: 282 },
  { tipo: "Tiempo", metrica: 193 },
  { tipo: "Tiempo", metrica: 333 },
  { tipo: "Tiempo", metrica: 289 },
  { tipo: "Tiempo", metrica: 166 },
  { tipo: "Tiempo", metrica: 295 },
  { tipo: "Tiempo", metrica: 522 },
  { tipo: "Tiempo", metrica: 96 },
  { tipo: "Tiempo", metrica: 137 },
  { tipo: "Tiempo", metrica: 302 },
  { tipo: "Tiempo", metrica: 183 },
  { tipo: "Tiempo", metrica: 585 },
  { tipo: "Tiempo", metrica: 251 },
  { tipo: "Tiempo", metrica: 506 },
  { tipo: "Tiempo", metrica: 457 },
  { tipo: "Tiempo", metrica: 173 },
  { tipo: "Tiempo", metrica: 238 },
  { tipo: "Tiempo", metrica: 65 },
  { tipo: "Tiempo", metrica: 462 },
  { tipo: "Tiempo", metrica: 106 },
  { tipo: "Tiempo", metrica: 512 },
  { tipo: "Tiempo", metrica: 213 },
  { tipo: "Tiempo", metrica: 309 },
  { tipo: "Tiempo", metrica: 339 },
  { tipo: "Tiempo", metrica: 234 },
  { tipo: "Tiempo", metrica: 208 },
  { tipo: "Tiempo", metrica: 242 },
  { tipo: "Tiempo", metrica: 63 },
  { tipo: "Tiempo", metrica: 554 },
  { tipo: "Tiempo", metrica: 443 },
  { tipo: "Tiempo", metrica: 387 },
  { tipo: "Tiempo", metrica: 187 },
  { tipo: "Tiempo", metrica: 312 },
  { tipo: "Tiempo", metrica: 111 },
  { tipo: "Tiempo", metrica: 353 },
  { tipo: "Tiempo", metrica: 218 },
  { tipo: "Tiempo", metrica: 208 },
  { tipo: "Tiempo", metrica: 301 },
  { tipo: "Tiempo", metrica: 111 },
  { tipo: "Tiempo", metrica: 313 },
];
export const mesRes = [
  { tipo: "Resolucion", metrica: 67 },
  { tipo: "Resolucion", metrica: 63 },
  { tipo: "Resolucion", metrica: 54 },
  { tipo: "Resolucion", metrica: 77 },
  { tipo: "Resolucion", metrica: 54 },
  { tipo: "Resolucion", metrica: 95 },
  { tipo: "Resolucion", metrica: 76 },
  { tipo: "Resolucion", metrica: 67 },
  { tipo: "Resolucion", metrica: 59 },
  { tipo: "Resolucion", metrica: 73 },
  { tipo: "Resolucion", metrica: 95 },
  { tipo: "Resolucion", metrica: 75 },
  { tipo: "Resolucion", metrica: 58 },
  { tipo: "Resolucion", metrica: 72 },
  { tipo: "Resolucion", metrica: 97 },
  { tipo: "Resolucion", metrica: 51 },
  { tipo: "Resolucion", metrica: 85 },
  { tipo: "Resolucion", metrica: 62 },
  { tipo: "Resolucion", metrica: 62 },
  { tipo: "Resolucion", metrica: 70 },
  { tipo: "Resolucion", metrica: 83 },
  { tipo: "Resolucion", metrica: 81 },
  { tipo: "Resolucion", metrica: 70 },
  { tipo: "Resolucion", metrica: 96 },
  { tipo: "Resolucion", metrica: 92 },
  { tipo: "Resolucion", metrica: 66 },
  { tipo: "Resolucion", metrica: 64 },
  { tipo: "Resolucion", metrica: 70 },
  { tipo: "Resolucion", metrica: 95 },
  { tipo: "Resolucion", metrica: 54 },
  { tipo: "Resolucion", metrica: 64 },
  { tipo: "Resolucion", metrica: 69 },
  { tipo: "Resolucion", metrica: 83 },
  { tipo: "Resolucion", metrica: 58 },
  { tipo: "Resolucion", metrica: 83 },
  { tipo: "Resolucion", metrica: 58 },
  { tipo: "Resolucion", metrica: 64 },
  { tipo: "Resolucion", metrica: 87 },
  { tipo: "Resolucion", metrica: 83 },
  { tipo: "Resolucion", metrica: 87 },
  { tipo: "Resolucion", metrica: 80 },
  { tipo: "Resolucion", metrica: 59 },
  { tipo: "Resolucion", metrica: 55 },
  { tipo: "Resolucion", metrica: 78 },
  { tipo: "Resolucion", metrica: 73 },
  { tipo: "Resolucion", metrica: 89 },
  { tipo: "Resolucion", metrica: 68 },
  { tipo: "Resolucion", metrica: 65 },
  { tipo: "Resolucion", metrica: 62 },
  { tipo: "Resolucion", metrica: 68 },
  { tipo: "Resolucion", metrica: 90 },
  { tipo: "Resolucion", metrica: 64 },
  { tipo: "Resolucion", metrica: 76 },
  { tipo: "Resolucion", metrica: 96 },
  { tipo: "Resolucion", metrica: 76 },
  { tipo: "Resolucion", metrica: 74 },
  { tipo: "Resolucion", metrica: 88 },
  { tipo: "Resolucion", metrica: 72 },
  { tipo: "Resolucion", metrica: 65 },
  { tipo: "Resolucion", metrica: 99 },
];
export const mesAbandono = [
  { tipo: "Abandono", metrica: 4 },
  { tipo: "Abandono", metrica: 8 },
  { tipo: "Abandono", metrica: 18 },
  { tipo: "Abandono", metrica: 9 },
  { tipo: "Abandono", metrica: 19 },
  { tipo: "Abandono", metrica: 15 },
  { tipo: "Abandono", metrica: 20 },
  { tipo: "Abandono", metrica: 1 },
  { tipo: "Abandono", metrica: 22 },
  { tipo: "Abandono", metrica: 17 },
  { tipo: "Abandono", metrica: 14 },
  { tipo: "Abandono", metrica: 13 },
  { tipo: "Abandono", metrica: 18 },
  { tipo: "Abandono", metrica: 21 },
  { tipo: "Abandono", metrica: 23 },
  { tipo: "Abandono", metrica: 7 },
  { tipo: "Abandono", metrica: 18 },
  { tipo: "Abandono", metrica: 16 },
  { tipo: "Abandono", metrica: 3 },
  { tipo: "Abandono", metrica: 3 },
  { tipo: "Abandono", metrica: 21 },
  { tipo: "Abandono", metrica: 22 },
  { tipo: "Abandono", metrica: 24 },
  { tipo: "Abandono", metrica: 10 },
  { tipo: "Abandono", metrica: 18 },
  { tipo: "Abandono", metrica: 26 },
  { tipo: "Abandono", metrica: 22 },
  { tipo: "Abandono", metrica: 7 },
  { tipo: "Abandono", metrica: 10 },
  { tipo: "Abandono", metrica: 2 },
  { tipo: "Abandono", metrica: 4 },
  { tipo: "Abandono", metrica: 19 },
  { tipo: "Abandono", metrica: 24 },
  { tipo: "Abandono", metrica: 13 },
  { tipo: "Abandono", metrica: 13 },
  { tipo: "Abandono", metrica: 13 },
  { tipo: "Abandono", metrica: 24 },
  { tipo: "Abandono", metrica: 27 },
  { tipo: "Abandono", metrica: 3 },
  { tipo: "Abandono", metrica: 24 },
  { tipo: "Abandono", metrica: 16 },
  { tipo: "Abandono", metrica: 27 },
  { tipo: "Abandono", metrica: 5 },
  { tipo: "Abandono", metrica: 26 },
  { tipo: "Abandono", metrica: 14 },
  { tipo: "Abandono", metrica: 25 },
  { tipo: "Abandono", metrica: 10 },
  { tipo: "Abandono", metrica: 0 },
  { tipo: "Abandono", metrica: 8 },
  { tipo: "Abandono", metrica: 19 },
  { tipo: "Abandono", metrica: 17 },
  { tipo: "Abandono", metrica: 2 },
  { tipo: "Abandono", metrica: 21 },
  { tipo: "Abandono", metrica: 18 },
  { tipo: "Abandono", metrica: 9 },
  { tipo: "Abandono", metrica: 21 },
  { tipo: "Abandono", metrica: 11 },
  { tipo: "Abandono", metrica: 17 },
  { tipo: "Abandono", metrica: 25 },
  { tipo: "Abandono", metrica: 23 },
];
export const mesVelocidad = [
  { tipo: "Velocidad", metrica: 54 },
  { tipo: "Velocidad", metrica: 38 },
  { tipo: "Velocidad", metrica: 29 },
  { tipo: "Velocidad", metrica: 49 },
  { tipo: "Velocidad", metrica: 47 },
  { tipo: "Velocidad", metrica: 22 },
  { tipo: "Velocidad", metrica: 44 },
  { tipo: "Velocidad", metrica: 23 },
  { tipo: "Velocidad", metrica: 36 },
  { tipo: "Velocidad", metrica: 29 },
  { tipo: "Velocidad", metrica: 5 },
  { tipo: "Velocidad", metrica: 5 },
  { tipo: "Velocidad", metrica: 5 },
  { tipo: "Velocidad", metrica: 46 },
  { tipo: "Velocidad", metrica: 43 },
  { tipo: "Velocidad", metrica: 33 },
  { tipo: "Velocidad", metrica: 17 },
  { tipo: "Velocidad", metrica: 49 },
  { tipo: "Velocidad", metrica: 30 },
  { tipo: "Velocidad", metrica: 38 },
  { tipo: "Velocidad", metrica: 26 },
  { tipo: "Velocidad", metrica: 33 },
  { tipo: "Velocidad", metrica: 25 },
  { tipo: "Velocidad", metrica: 34 },
  { tipo: "Velocidad", metrica: 6 },
  { tipo: "Velocidad", metrica: 54 },
  { tipo: "Velocidad", metrica: 37 },
  { tipo: "Velocidad", metrica: 14 },
  { tipo: "Velocidad", metrica: 27 },
  { tipo: "Velocidad", metrica: 33 },
  { tipo: "Velocidad", metrica: 17 },
  { tipo: "Velocidad", metrica: 46 },
  { tipo: "Velocidad", metrica: 23 },
  { tipo: "Velocidad", metrica: 17 },
  { tipo: "Velocidad", metrica: 46 },
  { tipo: "Velocidad", metrica: 27 },
  { tipo: "Velocidad", metrica: 36 },
  { tipo: "Velocidad", metrica: 13 },
  { tipo: "Velocidad", metrica: 10 },
  { tipo: "Velocidad", metrica: 42 },
  { tipo: "Velocidad", metrica: 14 },
  { tipo: "Velocidad", metrica: 46 },
  { tipo: "Velocidad", metrica: 46 },
  { tipo: "Velocidad", metrica: 19 },
  { tipo: "Velocidad", metrica: 49 },
  { tipo: "Velocidad", metrica: 9 },
  { tipo: "Velocidad", metrica: 51 },
  { tipo: "Velocidad", metrica: 51 },
  { tipo: "Velocidad", metrica: 54 },
  { tipo: "Velocidad", metrica: 1 },
  { tipo: "Velocidad", metrica: 25 },
  { tipo: "Velocidad", metrica: 52 },
  { tipo: "Velocidad", metrica: 13 },
  { tipo: "Velocidad", metrica: 36 },
  { tipo: "Velocidad", metrica: 18 },
  { tipo: "Velocidad", metrica: 4 },
  { tipo: "Velocidad", metrica: 22 },
  { tipo: "Velocidad", metrica: 26 },
  { tipo: "Velocidad", metrica: 14 },
  { tipo: "Velocidad", metrica: 36 },
];
